spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crm?useSSL=false
    username: root
    password: 12345678
  r2dbc:
    url: r2dbc:mysql://root:12345678@127.0.0.1:3306/crm
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.order_updates: true
      hibernate.order_inserts: true
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.jdbc.fetch_size: 500
      hibernate.jdbc.batch_size: 500
